# BOWPreishoheit/src/Resources/config/packages/monolog.yaml

monolog:
  channels: 
    - 'bow_preishoheit'

  handlers:
    bowPreishoheitLogHandler:
      type: rotating_file
      path: "%kernel.logs_dir%/bow_preishoheit_%kernel.environment%.log"
      level: error
      channels: ["bow_preishoheit"]
